config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users

  resources :articles do
    resources :comments
  end

  get 'izraeli_ids/new' => 'izraeli_ids#new'
  post 'izraeli_ids/result' => 'izraeli_ids#result'

  root 'welcome#index'

end

app/controllers/izraeli_ids_controller.rb
class IzraeliIdsController < ApplicationController
  def new

  end

  def result
    @izraeli_id = params[:izraeli_id]
    @result = check(@izraeli_id)
  end

  private

  def check(izraeli_id)
    id_array = izraeli_id.split('')
    sum = sum_izraeli_id(id_array)
    return (sum % 10) == 0
  end

  def sum_izraeli_id(id_array)
    sum = 0
    id_array.each_with_index do |value, index|
      if value.to_i.to_s == value
        if index % 2 == 0
          sum += value.to_i
        else
          double_value = value.to_i * 2
          if double_value < 10
            sum += double_value
          else
            sum += double_value / 10 + double_value % 10
          end
        end
      else
        return false
      end
    end
    sum
  end

end

app/helpers/izraeli_ids_helper.rb
module IzraeliIdsHelper
end

app/views/izraeli_ids/new.html.haml
%h1 New
.panel.panel-default
  .panel-body
    = form_tag izraeli_ids_result_path do
      .form-group
        = text_field_tag :izraeli_id, '', class: 'form-control'
      = button_tag :submit, class: 'btn btn-default'

app/views/izraeli_ids/result.html.haml
%h1 Results
.panel.panel-default
  .panel-body
    = @izraeli_id
    is
    = @result